### ISSUE TITLE
New tab button (+) should be right next to the last tab opened

### ISSUE THREAD

**Issue by baudren** [liri-browser/liri-browser#100]
Right now, the new tab button sits at the far right of the screen (at least on Windows 8.1). The place where we would naturally expect it is right next to the last opened one, as it is naturally here that we search for it (that maybe a recent thing, though, but currently all the other browsers do that).

**Comment by VirusKA** [comment]
i agree.

**Comment by theRealPadster** [comment]
Yeah, it had me confused for a second

**Comment by jmc-figueira** [comment]
If you're coming from a Chrome background, definitely, but, for instance, Safari does it the way Liri does, with the '+' button always at the right. It comes down to a matter of taste/consistency I believe.

**Comment by baudren** [comment]
True - there is the point of view of habit. I did not know about Safari, but to have the `new tab` button right next to the tabs is common to Chrome, Firefox and Internet Explorer (including Edge).

But more than this, it is an issue of user experience. When just a few tabs are open, we interact with tabs in several way:
- look at which ones are open (visually located first on the left)
- switch to other tabs (also on the left, though accessible by keyboard)
- close (also on the left)
- open new ones (should be with the rest).

The discrepancy between far left and far right of the screen is increased when using a wide screen - which is today standard on desktop. By moving the button with the tabs, we have a consistent user experience that minimizes the need to scan different parts of the screen for a related set of activities.

**Comment by VirusKA** [comment]
This is a decision to rest on whoever is doing the designs for liri browser.

**Comment by baudren** [comment]
@VirusKA for sure! I was just pointing out my opinion and the facts on which I built it.

**Comment by VirusKA** [comment]
@pierremtb what's your opinion on this?

**Comment by tim-sueberkrueb** [comment]
Liri used to have this feature in v0.2. It got removed meanwhile I integrated the new drag+drop tab system for v0.3. Just integrated it again :) IMO, it should be handled this way, @pierremtb?
![bildschirmfoto vom 2015-10-04 11 47 19](https://cloud.githubusercontent.com/assets/11774614/10267253/b097c2f2-6a8d-11e5-842a-6f2907bf0391.png)

**Comment by VirusKA** [comment]
IDK why, but that somehow made the design a lot less jarring! looks better and better everyday!

**Comment by pierremtb** [comment]
@tim-sueberkrueb Nice ! We should also set the tab bar width to its content width, in order to make the drag area wider if only one or two tabs are opened (and also reduce the tab size if a lot of tabs are opened, like no page title)

**Comment by tim-sueberkrueb** [comment]
@pierremtb +1, see #109
