### ISSUE TITLE
Liri Crash on Windows 10

### ISSUE THREAD

**Issue by jonsmith500** [liri-browser/liri-browser#102]
I tried liri browser 0.3 portable on Windows 10 and at the first time liri run, apparently, ok. I changed some configurations of the browser and then i saw that configurations are not applied. I restarted the browser and then liri crash. I restored the liri browser downloading  a new copy but now always liri crash including at first time. Also i tried the liri installer with the same result.
In debug file says:
[0926/143411:ERROR:resource_bundle.cc(691)] Failed to load C:\Qt\Qt5.5.0\5.5\msvc2013\qtwebengine_resources.pak
Some features may not be available.
[0926/143411:WARNING:resource_bundle.cc(304)] locale_file_path.empty()

The problem is the browser or my computer?

**Comment by VirusKA** [comment]
Your package might be corrupt. Try deleting the original browser and reinstalling.

**Comment by jonsmith500** [comment]
I reistalled liri 0.3 with the same error but I looked for the problem and i found the solution. 
My reference page is: 
https://forum.qt.io/topic/52666/error-resource_bundle-cc-639-failed-to-load-qtwebengine_resources-pak

The problem is that portable and installer version not have the file "qt.conf" in the main folder. I created it manually and the browser finally work but the application still crash continuously without a debug file to view the reason of the error. The application work me when trying run it repeatedly and when the application work i create a new window... new crash. Why? I don't know.

Please fix it for next version of liri. Is a cool browser.
Thanks for everything

Note: The value of the "qt.conf" file is:
[Paths]
Prefix=.

**Comment by tim-sueberkrueb** [comment]
@jonsmith500 thank you! We'll take care of that.
