### ISSUE TITLE
Suggestion - Custom Search Engines

### ISSUE THREAD

**Issue by Vivahex** [liri-browser/liri-browser#104]
As suggested on G+, just moving to an issue here:

Ability to set our own custom search engines such as in google chrome
Name: Google Play Store
Keyword: gps
Link: https://play.google.com/store/search?q=%s
would mean that when typing "gps[tab]" in the address bar would return whatever is entered after the tab into the search query for play store.

It's one thing I keep doing as I'm so used to having multiple custom search engines on Google Chrome

**Comment by RockyTV** [comment]
I would like to suggest to allow the user to implement a custom keyword to search on a specified search engine. 

For example, I set the custom keyword for Google Play Store to !gps. When I search something in the address bar, and add !gps to it, it searches the Google Play Store for whatever I wanted to search.

**Comment by Vivahex** [comment]
^ Yeah, that's what I was saying :P "gps" would be the equivalent of your "!gps", user set values for name/keyword/link

**Comment by pierremtb** [comment]
Done ;)

Tutorial :
*You enter your keyword
![capture du 2015-10-05 23 08 37](https://cloud.githubusercontent.com/assets/10795683/10293697/4a9b1df8-6bb6-11e5-8fa1-92212f69d370.png)
*Hit Tab 
![capture du 2015-10-05 23 08 40](https://cloud.githubusercontent.com/assets/10795683/10293716/63089118-6bb6-11e5-8f74-49fa3e820ec7.png)
*Type your query (or Shift+Tab to discard)
![capture du 2015-10-05 23 08 48](https://cloud.githubusercontent.com/assets/10795683/10293727/6c6f33d8-6bb6-11e5-831e-fc0d02aa9ead.png)
*Hit Enter : your search query is launched
![capture du 2015-10-05 23 08 51](https://cloud.githubusercontent.com/assets/10795683/10293748/8b2d5c46-6bb6-11e5-8aa2-f3a442111146.png)

You can see the presets on a dedicated settings page : 
![capture du 2015-10-05 23 09 43](https://cloud.githubusercontent.com/assets/10795683/10293768/9fe794ee-6bb6-11e5-85f0-9f34ac467f3c.png)
Here I added a custom one (no save button, it's automatic)
And I can use it like previously : 
![capture du 2015-10-05 23 09 52](https://cloud.githubusercontent.com/assets/10795683/10293787/c08daf08-6bb6-11e5-89d7-f1ba62647284.png)

**Comment by tim-sueberkrueb** [comment]
@pierremtb cool!
