### ISSUE TITLE
Add a dark-theme

### ISSUE THREAD

**Issue by pierremtb** [liri-browser/liri-browser#106]
For users who love dark interfaces. The theme color option would be disable if selected

**Comment by tim-sueberkrueb** [comment]
+1, there could be this options:
( x ) dark theme
----  (  ) always on
---- (  ) automatically from ( 24:00 ) till ( 08: 00)

(   ) light theme

**Comment by VirusKA** [comment]
i desperately want a dark theme

**Comment by pierremtb** [comment]
@VirusKA Well here it is ;)
![capture du 2015-10-03 22 57 43](https://cloud.githubusercontent.com/assets/10795683/10265097/78292de0-6a22-11e5-9435-9fb7566fe306.png)
(Some labels still need to be themed, but I need to dig more, but the integration is done)
