### ISSUE TITLE
Enhancement: Have a 1px border on each tab

### ISSUE THREAD

**Issue by VirusKA** [liri-browser/liri-browser#108]
This is just an aesthetic thing that's been bothering me. It help distinguish the individual tabs.

**Comment by pierremtb** [comment]
I tried, but it looks a lot worse. I like it without. What do you think @tim-sueberkrueb ?
(I close this for now)

**Comment by VirusKA** [comment]
can i get a picture? i never saw it visually but i thought in my mind it was a good idea.
