### ISSUE TITLE
Address bar does not update when switching tabs

### ISSUE THREAD

**Issue by RockyTV** [liri-browser/liri-browser#112]
How to reproduce:
- Open 2 tabs
- In one, navigate to a site.
- In the other one, navigate to another site.
- When you switch tabs, the address bar text label will have the last typed address, instead of displaying the current tab's site address.

Tested on latest commit f46cc84

**Comment by jmc-figueira** [comment]
Can confirm, this is also happening to me recently. Something might have been broken by the custom search engines commit (f46cc8462ceb10ef6d2744c0512b5d8f0928a7f9)

**Comment by pierremtb** [comment]
@jmc-figueira @RockyTV Yeah, that's what I feared when implemented QuickSearches. Thanks for pointing it out.

**Comment by pierremtb** [comment]
@RockyTV You just forgot a point : you need to activate a QuickSearch first, leave it, and then it is as descritped

**Comment by pierremtb** [comment]
@RockyTV @jmc-figueira Should be fixed with the last commit, please report
