### ISSUE TITLE
shortcut to focus on url bar

### ISSUE THREAD

**Issue by Haroenv** [liri-browser/liri-browser#125]
I'd propose `mod+L` like on other browsers. Also would be useful to autofocus on it when opening a new tab.

**Comment by theRealPadster** [comment]
You mean ctrl+L?
I thought mod key usually meant "windows key"

**Comment by Haroenv** [comment]
I meant `⌘+L` actually, but I guess that'd be `ctrl` on Linux

**Comment by pierremtb** [comment]
Same problem as #126
