### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by tim-sueberkrueb** [liri-browser/liri-browser#21]
We need an icon for this app :)

**Comment by pierremtb** [comment]
But first we need a real name ;)

**Comment by tim-sueberkrueb** [comment]
@pierremtb Okay, that needs an issue too :)

**Comment by loctauxphilippe** [comment]
Now that the name is known, you need an icon :)

**Comment by tim-sueberkrueb** [comment]
yeah :) @pierremtb made this (organization icon):
![Icon](https://avatars1.githubusercontent.com/u/14042592?v=3&s=200)
https://github.com/liri-browser
 I love it apart from the magnifying glass.

**Comment by loctauxphilippe** [comment]
@tim-sueberkrueb if the icon has been made, you can close this issue :)

**Comment by pierremtb** [comment]
I think this will be good for now 
![liri-bird-shape](https://cloud.githubusercontent.com/assets/10795683/9741470/e09abdfc-565a-11e5-9a4e-935e05ada69d.png)

**Comment by loctauxphilippe** [comment]
@pierremtb bon travail! :)

**Comment by pierremtb** [comment]
@loctauxphilippe Merci :)

**Comment by tim-sueberkrueb** [comment]
@loctauxphilippe @pierremtb Je ne parle pas français :)

**Comment by loctauxphilippe** [comment]
I just said good work :)
Allright I won't speak French anymore l, so everyone can understand

**Comment by tim-sueberkrueb** [comment]
@pierremtb no problem, you can, what else do we have Google Translator for :)

**Comment by loctauxphilippe** [comment]
:)
