### ISSUE TITLE
Find a real name

### ISSUE THREAD

**Issue by tim-sueberkrueb** [liri-browser/liri-browser#23]
"Material Browser" is not really a creative name :)
I think we need something more unique.

If this browser gets default on Papyros it could just called "Browser App" similar to the Ubuntu (Touch) Browser.

**Comment by chifreaigle** [comment]
What about : "Navire"

**Comment by pierremtb** [comment]
@chifreaigle beautiful name (and french haha)

**Comment by VirusKA** [comment]
what does "Navire" mean?

**Comment by chifreaigle** [comment]
@VirusKA  It means a ship, (french word)

**Comment by VirusKA** [comment]
What about "Quantum"? (Google's codename for Material Design)

**Comment by tim-sueberkrueb** [comment]
We finally decided to name it "Liri Browser". 
@VirusKA, @chifreaigle thanks for your suggestions! (And don't hate me, Karim (: ).
