### ISSUE TITLE
Improve view-source feature

### ISSUE THREAD

**Issue by pierremtb** [liri-browser/liri-browser#34]

**Comment by pierremtb** [comment]
Added, but needs improvements, as syntax highlighting (I don't know if it's possible however)

**Comment by pierremtb** [comment]
![screen](http://s8.postimg.org/69264gw90/Screenshot_from_2015_07_30_23_26_56.jpg)

**Comment by VirusKA** [comment]
We're not planning on adding developer tools n stuff right?

**Comment by pierremtb** [comment]
@VirusKA Hard to say, it would need a huge amount of work. Just added this because it was easy and sometimes useful.

**Comment by tim-sueberkrueb** [comment]
@pierremtb Can this be closed? :)

**Comment by pierremtb** [comment]
Nope, need to fix some bugs

**Comment by pierremtb** [comment]
But it has improved a lot 
![feature_source](https://cloud.githubusercontent.com/assets/10795683/9670678/e9408ade-528d-11e5-8f3b-9f02383285ae.png)

**Comment by VirusKA** [comment]
^ deserves  :clap:  :clap: 
you even mae the background dark for developers

**Comment by pierremtb** [comment]
@VirusKA Thanks.

I'ma close this, and open a more-specific one. 
We can now view source in a new tab (with syntax-highlighting and auto-indent.)
(Next feature will be syntax-theme support)
![sans titre-1](https://cloud.githubusercontent.com/assets/10795683/9701061/cbd08c82-5419-11e5-9ffb-4b5951106886.png)
