### ISSUE TITLE
Makefile oddness

### ISSUE THREAD

**Issue by anowlcalledjosh** [liri-browser/liri-browser#37]
When the Linux install script `make`s `material-browser`, this happens:

```
cp -f -R [truncated]/build/material-browser/translations [truncated]/build/material-browser
cp: ‘[truncated]/build/material-browser/translations’ and ‘[truncated]/build/material-browser/translations’ are the same file
make: *** [copydata] Error 1
```

**Comment by pierremtb** [comment]
I think you fixed this @tim-sueberkrueb, don't you ?

**Comment by tim-sueberkrueb** [comment]
@pierremtb Not really, I just commented out the translations copying part which was causing it. We need to figure out how to handle this correctly. Can stay closed though.
