### ISSUE TITLE
Install script is fragile & uses material-browser repo

### ISSUE THREAD

**Issue by anowlcalledjosh** [liri-browser/liri-browser#38]
Title says it all. I've made a version that uses the new repo (liri-browser as opposed to material-browser), keeps logs, checks that the Qt install directory exists and asks if Qt is already installed. Oh, and it gets the user's name too :-)

**Comment by tim-sueberkrueb** [comment]
@anowlcalledjosh great work! May update the script to your version?

**Comment by anowlcalledjosh** [comment]
@tim-sueberkrueb sure!

**Comment by tim-sueberkrueb** [comment]
@anowlcalledjosh thank you, done :)
