### ISSUE TITLE
Package?

### ISSUE THREAD

**Issue by loctauxphilippe** [liri-browser/liri-browser#4]
hey!
I like your browser!
Could you give me the list of all the dependencies of the app and a working Makefile?
If I got time, I'll try to make a debian package :-)

**Comment by tim-sueberkrueb** [comment]
Hey @loctauxphilippe, this would be fantastic!
You should be able to build it for Debian/Ubuntu using this instructions: https://github.com/tim-sueberkrueb/material-browser#dependencies.
I'm not familar with debian packaging, but one problem might be that this browser requires the latest Qt 5.5 (which is currently in beta phase and will probably released 23rd June 2015).
Thanks anyway and glad you like it :)

**Comment by loctauxphilippe** [comment]
@tim-sueberkrueb good! But I have a problem: papyros's stuff are not in launchpad so I can't build the package for the moment

**Comment by crutchcorn** [comment]
@loctauxphilippe, can you please package qt5.5 so that I can make a script for Papyros install and so that this kind man could have his app packaged? ;) I can at lease figure out things from there and get papyros all figured out on Ubuntu

**Comment by pierremtb** [comment]
@crutchcorn As Papyros will be Arch-based, it can use arch-packages, and I think qt5.5 is already packaged in Papyros repo.

**Comment by crutchcorn** [comment]
That's okay @pierremtb

**Comment by loctauxphilippe** [comment]
@tim-sueberkrueb does the script still work? or you have to rewrite it again?

**Comment by tim-sueberkrueb** [comment]
@loctauxphilippe should be fine :) I recently updated it to download Qt 5.5 final release.

**Comment by loctauxphilippe** [comment]
@tim-sueberkrueb cool ;)

**Comment by VirusKA** [comment]
this appears to be done. I say close this issue

**Comment by pierremtb** [comment]
@VirusKA Sure, thank you for pointing this out
