### ISSUE TITLE
OS X Support

### ISSUE THREAD

**Issue by biscuitpants** [liri-browser/liri-browser#40]
Is support for OS X coming in the near future?

**Comment by pierremtb** [comment]
OS X is supported, but you need to compile it yourself (I'm sorry but I can't upload builds, I don't have a Mac).

**Comment by pierremtb** [comment]
@biscuits If you have time, you could build it for us :)

**Comment by biscuitpants** [comment]
Yeah of course! How do I build it? I've got brew and all of that installed.

**Comment by pierremtb** [comment]
@biscuitpants Make sure you have Qt5.5 and QtWebEngine 1.1. Then clone the repo, run qmake and make in the directory. It is working, then you can try macdeployqt.

**Comment by biscuitpants** [comment]
Is QT supported on OSX?

**Comment by tim-sueberkrueb** [comment]
@biscuitpants yes, it is. You can get it here: http://qt.io/download-open-source

**Comment by tim-sueberkrueb** [comment]
Oooooops :) wrong issue xD

**Comment by VirusKA** [comment]
I have a mac too but QT acts very strange for me, so i can't test aything papyros related :(

**Comment by iBeliever** [comment]
I'm running the app on OS X, and it works perfectly. I'm using the `qt5` package from [Homebrew](http://brew.sh). Building is very simple, either using Qt Creator or `qmake` and `make`.

**Comment by pierremtb** [comment]
I got it running on OS X too, but using the official online installer, and setting the path for qmake. I will try to make OS X builds in a near future :)
