### ISSUE TITLE
Fix too-long-string-problem on source code viewer

### ISSUE THREAD

**Issue by pierremtb** [liri-browser/liri-browser#43]
We actually can't display source of some websites, because of URL limitations. Need to find another way to send the source code (http request is an option, but we need a real server)
![sans titre-12](https://cloud.githubusercontent.com/assets/10795683/9701114/597fa4f8-541c-11e5-9ecb-8a3a86e8b72d.png)

**Comment by tim-sueberkrueb** [comment]
@pierremtb what about doing the whole thing local?

**Comment by pierremtb** [comment]
@tim-sueberkrueb I'd like too, but i couldn't manage to load a local file in the webengine. If you can do it, tell me how :)

**Comment by iBeliever** [comment]
@pierremtb Have you tried using `Qt.resolvedUrl()` to get the URL to a local file?

**Comment by pierremtb** [comment]
@iBeliever No, that's a good idea

**Comment by pierremtb** [comment]
Finally fixed ! Still a distant html template file, but Liri sets now the content locally.
![capture du 2015-09-10 03 19 14](https://cloud.githubusercontent.com/assets/10795683/9777989/ee9f0a3c-576a-11e5-8f35-e1d9d4a85c33.png)
