### ISSUE TITLE
[Suggestion] Hide tab bar when only one tab is opened

### ISSUE THREAD

**Issue by iBeliever** [liri-browser/liri-browser#47]
This would save space when you only have one tab open. When the tab bar is hidden, the add tab button could be shown to the right of the address bar.

If this is something you would like to add, I can submit a pull request for this.

**Comment by pierremtb** [comment]
@iBeliever Good idea

**Comment by ianbrunelli** [comment]
This looks okay in the default mode, but really weird when using the integrated adressbars...
