### ISSUE TITLE
Move the settings from drawer to new tab page

### ISSUE THREAD

**Issue by pierremtb** [liri-browser/liri-browser#52]
The drawer won't be enough to add other settings

**Comment by tim-sueberkrueb** [comment]
(subpage on mobile)

**Comment by iBeliever** [comment]
:+1:

**Comment by pierremtb** [comment]
Done.
![capture du 2015-09-10 13 16 28](https://cloud.githubusercontent.com/assets/10795683/9786961/8f8d027a-57be-11e5-9dd2-07a2c098ea5b.png)

**Comment by tim-sueberkrueb** [comment]
@pierremtb Great work!
