### ISSUE TITLE
UI too tiny under Ubuntu Touch

### ISSUE THREAD

**Issue by zubozrout** [liri-browser/liri-browser#60]
Hi,
first of all I would very much like to thank you for bringing this to Ubuntu Touch. It is a much needed stuff on that platform.

As to the actual report, the UI renders really tiny on my Nexus 7 deb and Meizu MX4. It would be nice to count in DPI and resize the UI accordingly. I am not sure how to accomplish that but here is something on that topic: http://doc.qt.io/qt-5/scalability.html

Best,
Martin Kozub

**Comment by iBeliever** [comment]
This is a bug in the Material framework and maybe Qt itself. The framework is built to scale the UI as necessary, and doesn't use pixels directly. However, there seems to be issues with the DP scaling on some screens.

**Comment by tim-sueberkrueb** [comment]
This was fixed for:
* Meizu MX4
* BQ E4.5
* Nexus 4
* Nexus 7
Missing:
* Nexus 5
* BQ E5
See https://plus.google.com/+TimS%C3%BCberkr%C3%BCbDE/posts/PY75YZMjfH5

**Comment by tim-sueberkrueb** [comment]
Workarounds done :)
