### ISSUE TITLE
Shorten entire toolbar height. [Enhancement]

### ISSUE THREAD

**Issue by Polyg0n** [liri-browser/liri-browser#62]
Just as a suggestion, I would shorten the height of the browser toolbar (page-back/forward, refresh, omnibox, etc, etc) to 46 dp. 
It allows for more DOM space and looks a little more "sleek".

Just my opinion but something to mull over.

*(file & line edited):*
From: BrowserToolbar.qml; __Line: 13__ height: Units.dp(56)
To: BrowserToolbar.qml; __Line: 13__ height: Units.dp(46)

**Comment by iBeliever** [comment]
I do agree that it is quite tall, however, the Material Design spec does have tall toolbars on the desktop (and, oddly enough, specifies that toolbars are larger on the desktop than on mobile). If we deviate from the spec on this, it will look out of place with other MD apps - would we shrink the toolbar on all those tool? It's up to @tim-sueberkrueb and @pierremtb as they're the main devs, but my personal opinion is that we should stick to the spec as much as possible and hope that Google improves the desktop spec. However, at the same time, a browser is different in that the focus is on the DOM content and not the browser itself. So I think a good argument could also be made to shrink the toolbar height.

**Comment by Polyg0n** [comment]
Ah, that's very true. I had forgotten about the tall toolbars in the MD spec. 
Subtracting the height by 10dp didn't "drastically" change it. But agreed, it is up to @tim-sueberkrueb and @pierremtb.

**Comment by tim-sueberkrueb** [comment]
IMO we should keep the current height (due to consistency and mobile support).
@pierremtb?

**Comment by pierremtb** [comment]
@tim-sueberkrueb I agree
