### ISSUE TITLE
GitHub looks blurry in Liri

### ISSUE THREAD

**Issue by afollestad** [liri-browser/liri-browser#63]
I'm on OSX El Capitan.

<img width="1112" alt="screen shot 2015-09-12 at 7 03 10 pm" src="https://cloud.githubusercontent.com/assets/1820165/9834490/ffbe64bc-5980-11e5-85e3-5e402bedbf44.png">

**Comment by VirusKA** [comment]
Can't replicate on Yosemite. I'll keep trying

**Comment by afollestad** [comment]
It's probably because El Capitan is a developer preview, but it might be a sign that Liri won't work correctly once it becomes stable (due to changes in rendering or something).

**Comment by iBeliever** [comment]
This probably should be reported upstream in QtWebEngine once El Capitan is released (maybe now is okay too, not sure on their policy).

**Comment by VirusKA** [comment]
El Capitan released, I upgraded, no blurriness.
Whatever happened has disappeared.
