### ISSUE TITLE
No bars when "integrated addressbars" is enabled and only one tab is open

### ISSUE THREAD

**Issue by ianbrunelli** [liri-browser/liri-browser#71]
This issue was introduced by #51.

![captura de tela de 2015-09-13 11-34-49](https://cloud.githubusercontent.com/assets/5755892/9837135/c5d71d94-5a0b-11e5-89b0-7052c84b840e.png)

I particularly believe #47 (the issue that originated PR #51) conflicts with #10. There's no way you can have both.

**Comment by pierremtb** [comment]
Fixed
