### ISSUE TITLE
Keep screen on when watching videos (Ubuntu Touch)

### ISSUE THREAD

**Issue by zubozrout** [liri-browser/liri-browser#78]
Now I am not really sure how to approach this but the default Ubuntu browser keeps screen on when a video is being played. This would be really great to have in Liri as well.
Apps can finally request to keep screen on - here is an example app: http://bazaar.launchpad.net/~mpredotka/active-screen/trunk/files
Thank you.

**Comment by tim-sueberkrueb** [comment]
Done :)
