### ISSUE TITLE
Application Icon don't show

### ISSUE THREAD

**Issue by elav** [liri-browser/liri-browser#82]
First of all, I love this browser. My report is about Liri Browser icon, which does not display correctly in ArchLinux. In fact, in the /usr/share/applications/liri-browser.desktop file icon points to the category Network.

[Desktop Entry]
Name=Liri
Comment=Browse the Internet
Keywords=internet;browser;explore;web;
GenericName=Web Browser
Exec=liri-browser
Icon=network
Terminal=false
StartupNotify=true
Type=Application
Categories=Network;Internet;QT;QML;WebBrowser;

**Comment by theRealPadster** [comment]
I noticed this as well, and commented on the AUR page. I fixed it on my system locally by copying the icons/liri-browser.png to /usr/share/icons and changing the .desktop file's "Icon=" line to "Icon=liri-browser"

**Comment by elav** [comment]
Well, I solved similarly. I just wanted to report it if it was a bug or something.

**Comment by tim-sueberkrueb** [comment]
@elav that's fine, thx :)

**Comment by theRealPadster** [comment]
Is it a bug related to the program, or just the PKGBUILD? It looked to me like the .desktop file was generated in the build process, so is it a application or packaging-level thing?

**Comment by tim-sueberkrueb** [comment]
@theRealPadster we don't provide a desktop file, it's up to the guy who packaged it.
