### ISSUE TITLE
Right mouse click functionality

### ISSUE THREAD

**Issue by jmc-figueira** [liri-browser/liri-browser#92]
It would be nice to have common browser right mouse click functionality available, such as "Open link in new tab" or "Save as..." when you right click a link, for instance. At the moment it seems to just use the default QWebEngine right click context menu. I will try to implement it myself for now.

**Comment by jmc-figueira** [comment]
[I managed to add a Dropdown context menu for opening links in new tabs/windows.](https://github.com/jmc-figueira/liri-browser/commit/1d2f5777e1748542b97ae45ad924be6cbcffccc6)

![Picture](https://cloud.githubusercontent.com/assets/6634716/9922092/6c99774e-5cdc-11e5-8f17-0300cc5c3a4c.png)

What I'm missing at the moment is the ability to save as a bookmark or add to the dash, since I haven't found a reliable way to get the title of the web page without having to load it, and both "addBookmark/ToDash" functions require it. I would also like a "Save as..." button for files, but I'm not sure how to go about detecting that a link contains a file (the way other browsers do it).

**Comment by pierremtb** [comment]
@jmc-figueira Very nice thank you !

**Comment by tim-sueberkrueb** [comment]
@jmc-figueira hey, cool!

**Comment by VirusKA** [comment]
so is this issue fixed?

**Comment by jmc-figueira** [comment]
The last commit (translations fix) is not merged yet, but the right click menu is there and working.

**Comment by pierremtb** [comment]
Added a right click material menu, even without link, with reload, view source, etc

**Comment by tim-sueberkrueb** [comment]
cool, great work @pierremtb @jmc-figueira!

**Comment by SolarPolarMan** [comment]
All I have is back, forward and reload. Even if I'm hovering on a link
