### ISSUE TITLE
View Source Font 

### ISSUE THREAD

**Issue by domi-a-philip** [liri-browser/liri-browser#93]
I suggest changing the current font for viewing the source to Roboto Mono. I believe it is the Material Design monospace font 

https://www.google.com/fonts/specimen/Roboto+Mono

**Comment by pierremtb** [comment]
@tim-sueberkrueb will kill me if I leave Hack. But it's a good idea, I didn't know that Roboto has a code variant.

**Comment by tim-sueberkrueb** [comment]
@pierremtb :'D Though I love Hack (and will use it independently of it not being MD) I think it would be better to make Hack optional and Roboto Mono default. I didn't knew that exists either. So yeah, won't kill ya if it's available as an option :)

**Comment by Polyg0n** [comment]
I will wholly agree with @tim-sueberkrueb, hack looks sooooo much better than Roboto Mono. I'd keep Hack at least as an option!

**Comment by VirusKA** [comment]
I'm also on team Hack, but options are above all.

**Comment by pierremtb** [comment]
Done. And I also added an option for font size.
![capture du 2015-10-06 14 32 00](https://cloud.githubusercontent.com/assets/10795683/10308597/178f75e0-6c37-11e5-94d1-1b9f32b531c4.png)
