### ISSUE TITLE
Add hover text on menu buttons

### ISSUE THREAD

**Issue by baudren** [liri-browser/liri-browser#99]
No matter how clear the icons are, some text is usually needed ([see this post](http://uxmyths.com/post/715009009/myth-icons-enhance-usability)). Particularly, the top three icons for new tab, favorite and additional options should have one hover text, at least. The previous, next and refresh are maybe less important, but to be consistent, it would be nice as well to have.

The other possibility, to have the text directly next to the icon would perharps be less appealing in terms of cleanliness of design - though. None of the other browser do this, though all of them have hover text on icons.

**Comment by pierremtb** [comment]
Done
![capture du 2015-10-05 20 48 28](https://cloud.githubusercontent.com/assets/10795683/10290127/947c6fd0-6ba2-11e5-9a36-6bcf22f93850.png)

**Comment by baudren** [comment]
Cool - thank you!
